languageCode = "en"
languageName = "English"
weight = 1

title = "/home/robert"
#logo = "img/robert.jpg"
#copyright = "Copy, _right?_ :thinking_face:"

[params]
isoCode = "en"
displayName = "EN"
rtl = false
dateFormat = "2 January 2006"
