baseURL = "https://brauser.io"
languageCode = "en-us"
title = "Roberts Logbuch"
theme = "cactus"
copyright = "Robert" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "Printer of Catan"
# url = "/categories/settlers-of-catan/"
# weight = 3
# 
# [[menu.main]]
# name = "Mathe"
# url = "/categories/math/"
# weight = 4

[[menu.main]]
name = "CV"
url = "https://github.com/Flipez/cv/raw/master/content-de.pdf"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  mathjax = true
  logo = "/images/robert.jpg"

  # Home page settings
  description = "Working with a lot of servers in a datacenter. Also SRE & YAML-Engineer. Lost his heart to Ruby and likes photography, mountain biking, traveling and movies."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/flipez" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/flipez"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/robert-müller-9429001b6/"
  [[params.social]]
    name = "email"
    link = "code@brauser.io"  # no need for "mailto:" in the head
